#ifndef BRILLO8_VM_CONFIG_H
#define BRILLO8_VM_CONFIG_H

#define BRILLO8_LED_RUN 12
#define BRILLO8_LED_FLASH 13

#define BRILLO8_BTN_PUSH 9
#define BRILLO8_BTN_FLASH 8

#define BRILLO8_BTN_IN0  0
#define BRILLO8_BTN_IN1  1
#define BRILLO8_BTN_IN2  2
#define BRILLO8_BTN_IN3  3
#define BRILLO8_BTN_IN4  4
#define BRILLO8_BTN_IN5  5
#define BRILLO8_BTN_IN6  6
#define BRILLO8_BTN_IN7  7

#define BRILLO8_SOFT_SERIAL_RX 10
#define BRILLO8_SOFT_SERIAL_TX 11

#define BRILLO8_DEFAULT_VECTOR_CAPACITY 10
#define BRILLO8_DEFAULT_STACK_SIZE 32

#define BRILLO8_VECTOR_EEPROM_ADDR 0x50

#endif